export default [
    {
      id: 1,
      image: 'https://github.com/Jose6348/Images_Projects/raw/refs/heads/main/Tatto_page/cobra.avif',
      name: 'Tatuagem de Cobra',
      description: 'Tatuagem de cobra realista no antebraço.',
      category: 'Realismo',
    },
    {
      id: 2,
      image: 'https://github.com/Jose6348/Images_Projects/blob/main/Tatto_page/tatuagem-minimalista-1.jpg?raw=true',
      name: 'Tatuagem Minimalista',
      description: 'Tatuagem minimalista de uma flor no pulso.',
      category: 'Minimalista',
    },
    {
      id: 3,
      image: 'https://github.com/Jose6348/Images_Projects/blob/main/Tatto_page/Leao.jpg?raw=true',
      name: 'Tatuagem de Leão',
      description: 'Tatuagem de leão em aquarela no ombro.',
      category: 'Aquarela',
    },
    {
      id: 4,
      image: 'https://github.com/Jose6348/Images_Projects/raw/refs/heads/main/Tatto_page/Old%20school.avif',
      name: 'Tatuagem Old School',
      description: 'Tatuagem de uma andorinhaa old school.',
      category: 'Old School',
    },
    {
      id: 5,
      image: 'https://github.com/Jose6348/Images_Projects/blob/main/Tatto_page/pontilhismo-tatuagens-3.png?raw=true',
      name: 'Tatuagem Pontilhismo',
      description: 'Tatuagem de mandala em pontilhismo.',
      category: 'Pontilhismo',
    },
    {
      id: 6,
      image: 'https://github.com/Jose6348/Images_Projects/blob/main/Tatto_page/pontilhismo-tatuagens-3.png?raw=true',
      name: 'Tatuagem Pontilhismo',
      description: 'Tatuagem de mandala em pontilhismo.',
      category: 'Pontilhismo',
    },
    {
      id: 7,
      image: 'https://github.com/Jose6348/Images_Projects/blob/main/Tatto_page/pontilhismo-tatuagens-3.png?raw=true',
      name: 'Tatuagem Pontilhismo',
      description: 'Tatuagem de mandala em pontilhismo.',
      category: 'Pontilhismo',
    },
    {
      id: 8,
      image: 'https://github.com/Jose6348/Images_Projects/blob/main/Tatto_page/pontilhismo-tatuagens-3.png?raw=true',
      name: 'Tatuagem Pontilhismo',
      description: 'Tatuagem de mandala em pontilhismo.',
      category: 'Ferracin',
    },
  ];